language: python
python:
  - "2.7"
install:
  - mkdir -p docs/_static
  - pip install -r requirements/dev.txt
  - pip install . --use-mirrors
script:
  - make lint
  - make lint_docs
  - coverage run s3_backups/tests.py
  - coverage report

